# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
builds:
  - id: yurtadm
    binary: yurtadm
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/yurtadm/yurtadm.go
    ldflags:
      - -s -w -X github.com/openyurtio/openyurt/pkg/projectinfo.gitVersion={{ .Tag }} -X github.com/openyurtio/openyurt/pkg/projectinfo.gitCommit={{ .ShortCommit }} -X github.com/openyurtio/openyurt/pkg/projectinfo.buildDate={{ .Date }}
    env:
      - CGO_ENABLED=0

archives:
  - format: tar.gz
    id: yurtadm-tgz
    wrap_in_directory: '{{ .Os }}-{{ .Arch }}'
    builds:
      - yurtadm
    name_template: '{{ .ArtifactName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
    files: [ LICENSE, README.md ]
  - format: zip
    id: yurtadm-zip
    builds:
      - yurtadm
    wrap_in_directory: '{{ .Os }}-{{ .Arch }}'
    name_template: '{{ .ArtifactName }}-{{ .Tag }}-{{ .Os }}-{{ .Arch }}'
    files: [ LICENSE, README.md ]

checksum:
  name_template: 'sha256sums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
