apiVersion: apps.openyurt.io/v1alpha1
kind: YurtAppDaemon
metadata:
  name: test
spec:
  selector:
    matchLabels:
      app: test
  nodepoolSelector:
    matchLabels:
      apps.openyurt.io/nodepool: shanghai
  workloadTemplate:
    deploymentTemplate:
      metadata:
        labels: 
          app: test
      spec:
        selector:
          matchLabels:
            app: test
        template:
          metadata:
            labels:
              app: test
          spec:
            containers:
              - name: main
                image: alpine


  
