apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: yurt-hub
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
  - apiGroups:
      - apps.openyurt.io
    resources:
      - nodepools
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - yurt-hub-cfg
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - pool-coordinator-yurthub-certs
    verbs:
      - list
      - watch
  - apiGroups:
      - "coordination.k8s.io"
    resources:
      - leases
    verbs:
      - get
      - update
  - apiGroups:
      - "discovery.k8s.io"
    resources: 
      - "endpointslices"
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - "endpoints"
    verbs:
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: yurt-hub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: yurt-hub
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:nodes
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yurt-hub-cfg
data:
  cache_agents: {{ .Values.yurtHub.cacheAgents | quote }}
  servicetopology: ""
  discardcloudservice: ""
  masterservice: ""
