FROM bitnami/kubectl:1.29

# Add the CRD installation script to the container
COPY ./hack/make-rules/crd_upgrader.sh /usr/local/bin/crd-upgrade.sh

# Add CRD YAML files to the container
COPY ./charts/yurt-manager/crds /crds
COPY ./charts/yurt-iot-dock/crds /crds

# Set the entrypoint to the CRD installation script
ENTRYPOINT ["/usr/local/bin/crd-upgrade.sh"]
