{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "yurt-iot-dock.fullname" . }}
  labels:
    {{- include "yurt-iot-dock.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: yurt-iot-dock
      control-plane: controller-manager
  endpoints:
    - port: metrics
      path: /metrics
{{- end }}
