apiVersion: apps.openyurt.io/v1alpha1
kind: YurtStaticSet
metadata:
  name: yurt-hub-cloud
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "yurthub.labels" . | nindent 4 }}
spec:
  staticPodManifest: yurthub
  template:
    metadata:
      labels:
        k8s-app: yurt-hub-cloud
    spec:
      volumes:
        - name: hub-dir
          hostPath:
            path: /var/lib/yurthub
            type: DirectoryOrCreate
        - name: kubernetes
          hostPath:
            path: /etc/kubernetes
            type: Directory
      containers:
        - name: yurt-hub
          image: {{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: hub-dir
              mountPath: /var/lib/yurthub
            - name: kubernetes
              mountPath: /etc/kubernetes
          command:
            - yurthub
            - --v=2
            - --bind-address={{ .Values.yurthubBindingAddr }}
            - --server-addr={{ .Values.kubernetesServerAddr }}
            - --node-name=$(NODE_NAME)
            - --bootstrap-file={{ .Values.bootstrapFile }}
            - --working-mode=cloud
            - --namespace={{ .Release.Namespace }}
            {{- if .Values.organizations }}
            - --hub-cert-organizations={{ .Values.organizations }}
            {{- end }}
            {{- if .nodePoolName }}
            - --nodepool-name={{ .Values.nodePoolName }}
            {{- end }}
          livenessProbe:
            httpGet:
              host: {{ .Values.yurthubBindingAddr }}
              path: /v1/healthz
              port: 10267
            initialDelaySeconds: 300
            periodSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              cpu: 150m
              memory: 150Mi
            limits:
              memory: 300Mi
          securityContext:
            capabilities:
              add: [ "NET_ADMIN", "NET_RAW" ]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      hostNetwork: true
      priorityClassName: system-node-critical
      priority: 2000001000


